/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.loginprojetointegrador;

/**
 *
 * @author gabriel
 */
public class LoginTelaFrame extends javax.swing.JPanel {

    /**
     * Creates new form LoginTelaFrame
     */
    public LoginTelaFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        entrarJButton = new javax.swing.JButton();
        cadastarJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 260, 360, 70));

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 360, 70));

        entrarJButton.setContentAreaFilled(false);
        entrarJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(entrarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, 310, 60));

        cadastarJButton.setContentAreaFilled(false);
        cadastarJButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(cadastarJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 710, 180, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/loginprojetointegrador/Tela login PI.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastarJButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton entrarJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField passwordField;
    // End of variables declaration//GEN-END:variables
}
